name: Selenium CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}/SeleniumReview_Pom_structure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install pytest selenium webdriver-manager

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests
        run: pytest Tests/test_homepage_form.py Tests/test_register.py -v

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: .
